### ISSUE TITLE
[Bug] Codeblock Rendering in Preview Mode

### ISSUE THREAD

**Issue by bwoah-md** [Erallie/colored-candy#4] opened 2024-08-28 20:12 UTC
![image](https://github.com/user-attachments/assets/90d57966-5730-4c76-a6ee-380f0be29037)

The rendering of codeblock in the preview mode is a little off 
if you closely look at the corners of the text on the left side, then you'll see the letters are getting cut from the top in the codeblock

**Comment by Erallie** [comment] 2024-08-28 20:35
Hi! Yes, I did notice that myself. Just haven't gotten around to fixing it yet. Thank you for creating an issue and pointing it out!

**Comment by Erallie** [comment] 2024-08-28 22:14
I implemented a fix. Needs more thorough testing though.

**Comment by ElsaTam** [comment] 2024-08-29 15:32
I tried it as thoroughly I could, but couldn't reproduce the issue.

**Comment by Erallie** [comment] 2024-08-29 15:44
@ElsaTam Can you also test it out to make sure that the text inside code blocks and inline code doesn't overflow outside the box it's in? To fix this, I just made code blocks overflow.

**Comment by ElsaTam** [comment] 2024-08-29 15:50
@Erallie Yes I saw it, and therefore tried to make the text overflow. But since it's a `<code>` tag and nothing get formatted inside, this is rather safe to put an overflow. So it's good: reading/editing, inline/block, embed, in blockquotes, etc.

**Comment by Erallie** [comment] 2024-08-29 17:19
@ElsaTam perfect! Thank you! I will close this issue now.

**Closed as completed by Erallie** 2024-08-29 17:19 UTC
Labels: bug, needs testing
